@startuml
!pragma teoz true
skinparam noteBorderColor Black
skinparam noteBorderThickness 1
skinparam noteBackgroundColor Yellow

skinparam sequence {
	BoxBorderColor Black
	BoxFontSize 20

	ArrowColor Black
	ArrowThickness 1

	ActorBorderColor Black
	ActorBorderThickness 3
	ActorBackgroundColor Business
	ActorFontSize 15

	ParticipantBorderColor Black
	ParticipantBorderThickness 1
	ParticipantBackgroundColor Business
	ParticipantFontSize 15

	LifeLineBorderColor Black
	LifeLineBorderThickness 1
	LifeLineBackgroundColor LightGray
}

actor "User"
box "Host Server"
	participant "Linux"
	participant "Kubelet"
  box "xPU Host Agent" #LightBlue
         participant "OPI Host Controller"
         participant "gRPC server"
  end box
	participant "xPU Device Plugin" #dodgerblue
	participant "CNI" #LightBlue
	participant "Pod"
end box
participant "kube-apiserver"
box "xPU"
  box "xPU Agent" #LightBlue
	participant "OPI xPU Controller"
  end box
  participant "OPI API"
end box

== xPU Agent Initialization ==

autonumber
"User" -> "OPI xPU Controller": deploy
activate "OPI xPU Controller"
"OPI xPU Controller" -> "OPI xPU Controller": config.json
"OPI xPU Controller" -> "OPI xPU Controller": start datasyncer
"OPI xPU Controller" -[#green]> "kube-apiserver"  : watch OPI CRDs
autonumber stop

== xPU Host Agent Initialization ==

autonumber
"User" -> "OPI Host Controller": deploy
activate "OPI Host Controller"
"OPI Host Controller" -> "OPI Host Controller": config.json
"OPI Host Controller" -> "OPI Host Controller": start datasyncer
"OPI Host Controller" -[#green]> "kube-apiserver": watch OPI CRDs
"OPI Host Controller" -> "gRPC server": Start gRPC server
activate "gRPC server"
autonumber stop


== Device Plugin Initialization ==
autonumber

"User" -> "Kubelet": network attachment definition (CNI config)
"User" -> "xPU Device Plugin": deploy
activate "xPU Device Plugin"

"xPU Device Plugin" -> "xPU Device Plugin": config.json
"xPU Device Plugin" -> "Linux": create log file
"xPU Device Plugin" -> "Linux" : Check host for requirements
"xPU Device Plugin" -> "Linux": net.Interfaces()

activate "xPU Device Plugin" #DarkGray
note right #DarkGray: <color #White>discover resources</color>

"Linux" --> "xPU Device Plugin": interface list

"xPU Device Plugin" -> "Linux" : os.Readlink /sys/class/net/<interface>/device/driver
"Linux" --> "xPU Device Plugin" : driver name

activate "xPU Device Plugin" #SlateGray
note right #SlateGray: <color #White>loop interfaces, build device list</color>

deactivate "xPU Device Plugin"

autonumber stop
"xPU Device Plugin" [hidden]-> "xPU Device Plugin"
autonumber resume

deactivate "xPU Device Plugin"

"xPU Device Plugin" -> "xPU Device Plugin": start GRPC
"xPU Device Plugin" -> "Kubelet": GRPC: register
"xPU Device Plugin" -> "Kubelet": GRPC: device list

deactivate "xPU Device Plugin"

== Pod Creation ==
autonumber

"User" -> "Kubelet": create pod
"Kubelet" -> "xPU Device Plugin": GRPC: Allocate(VF/SF)
activate "xPU Device Plugin"
"xPU Device Plugin" -> "gRPC server": GRPC: Allocate (VF/SF)
"gRPC server" -> "OPI Host Controller" : Create xPU Netdev CRD
"OPI Host Controller" -[#green]> "kube-apiserver" : Push xPU Netdev CRD
"kube-apiserver" -[#green]> "OPI xPU Controller": Notify xPU Netdev CR
"OPI xPU Controller" -> "OPI xPU Controller": Sync xPU Netdev CR
"OPI xPU Controller"->"OPI API": Invoke OPI API to create the netdev
"OPI API"-->"OPI xPU Controller": return success
"OPI xPU Controller"-[#green]>"kube-apiserver": Update status of xPU Netdev CR
"kube-apiserver" -[#green]> "OPI Host Controller": Notify xPU Netdev CR
"OPI Host Controller" -> "OPI Host Controller": Sync xPU Netdev CR
"OPI Host Controller" -->"gRPC server": return success
"gRPC server" -->"xPU Device Plugin": return success
"xPU Device Plugin" --> "Kubelet": GRPC: AllocateResponse()
deactivate "xPU Device Plugin"

autonumber stop
"Kubelet" -[#Red]>> "Pod" : <color:Red>Kubelet starts creating the pod around now
autonumber resume

"Kubelet" -> "CNI" : cmdAdd(VF/SF, namespace, config)
activate "CNI"
"CNI" -> "gRPC server" : Get IP address from VF/SF CRD
"gRPC server" --> "CNI" : IP Address
"CNI" -> "Pod" : place VF/SF in pod netns
"CNI" -> "Kubelet" : return 0

deactivate "CNI"

autonumber stop

== Pod Running ==

"Kubelet" -> "Pod" : start pod
"Pod" -> "Pod" : application start
activate "Pod"


== Pod Deletion ==
autonumber

"User" -> "Kubelet": delete pod
"Kubelet" -> "Pod" : stop pod
deactivate "Pod"
"Kubelet" -> "CNI" : cmdDel(VF/SF, config)
activate "CNI"
"CNI" -> "Pod" : VF/SF from pod to host netns
"Pod" --> "CNI" : VF/SF
"CNI" -> "CNI" : clear IPAM
"CNI" -> "gRPC server": clear IPAM
"gRPC server" -[#green]> "kube-apiserver": delete OPI Netdev CR
"kube-apiserver" -[#green]> "OPI xPU Controller": Notify delete xPU Netdev CR
"OPI xPU Controller"->"OPI API": Delete the VF/SF
"OPI API" --> "OPI xPU Controller": return success
"gRPC server" --> "CNI": return success
"CNI" --> "Kubelet": return 0
deactivate "CNI"



"Kubelet" -> "Pod" : delete pod
deactivate "Pod"

@enduml
